import type {
  AnalyticsEvent,
  DiscountContext,
  DiscountResult,
  FraudAssessmentRequest,
  FraudAssessmentResult,
  InventoryReservationRequest,
  InventoryReservationResult,
  Money,
  NotificationInput,
  PricingContext,
  PricingResult,
  RecommendationContext,
  RecommendationResult,
  ReturnRequestInput,
  ReturnRequestResult,
} from '../contracts/ecommerce';

export interface AuditLogger {
  record(action: string, subjectId: string, metadata: Record<string, unknown>): Promise<void>;
}

export interface EventBus {
  publish(event: AnalyticsEvent): Promise<void>;
}

export interface NotificationService {
  enqueue(input: NotificationInput): Promise<void>;
}

export interface DiscountEngine {
  evaluate(context: DiscountContext): Promise<DiscountResult>;
}

export interface PricingEngine {
  price(context: PricingContext): Promise<PricingResult>;
}

export interface RecommendationEngine {
  recommend(context: RecommendationContext): Promise<RecommendationResult>;
}

export interface FraudDetectionService {
  assess(request: FraudAssessmentRequest): Promise<FraudAssessmentResult>;
}

export interface InventoryService {
  reserve(request: InventoryReservationRequest): Promise<InventoryReservationResult>;
}

export interface ReturnsService {
  requestReturn(input: ReturnRequestInput): Promise<ReturnRequestResult>;
}

const zeroMoney = (currencyCode: string): Money => ({ amount: 0, currencyCode });

export class RuleBasedDiscountEngine implements DiscountEngine {
  async evaluate(context: DiscountContext): Promise<DiscountResult> {
    const acceptedCodes = context.discountCodes.filter((code) => code.trim().length > 0);
    return {
      acceptedCodes,
      rejectedCodes: [],
      estimatedSavings: acceptedCodes.length ? { amount: Math.round(context.subtotal.amount * 0.1), currencyCode: context.subtotal.currencyCode } : zeroMoney(context.subtotal.currencyCode),
    };
  }
}

export class DynamicPricingEngine implements PricingEngine {
  async price(context: PricingContext): Promise<PricingResult> {
    const demandMultiplier = context.demandScore > 80 && context.inventoryAvailable < 5 ? 1.08 : 1;
    const effectiveAmount = Math.round(context.variant.price.amount * demandMultiplier);
    return {
      basePrice: context.variant.price,
      effectivePrice: { amount: effectiveAmount, currencyCode: context.variant.price.currencyCode },
      reasonCodes: demandMultiplier > 1 ? ['high_demand_low_inventory'] : ['base_price'],
    };
  }
}

export class RulesRecommendationEngine implements RecommendationEngine {
  async recommend(context: RecommendationContext): Promise<RecommendationResult> {
    const uniqueProductIds = [...new Set([context.currentProduct?.id, ...context.viewedProductIds].filter(Boolean) as string[])];
    return {
      productIds: uniqueProductIds.slice(0, 8),
      strategy: context.currentProduct ? 'similar_products' : 'recently_viewed',
      generatedAt: new Date().toISOString(),
    };
  }
}

export class RiskScoringFraudService implements FraudDetectionService {
  async assess(request: FraudAssessmentRequest): Promise<FraudAssessmentResult> {
    const amountRisk = request.subtotal.amount > 50000 ? 35 : 5;
    const gatewayRisk = request.paymentGateway ? 0 : 15;
    const score = Math.min(100, amountRisk + gatewayRisk);
    return {
      decision: score >= 70 ? 'review' : 'approve',
      score,
      reasonCodes: score >= 70 ? ['manual_review_required'] : ['risk_within_threshold'],
    };
  }
}

export class InventoryReservationService implements InventoryService {
  async reserve(request: InventoryReservationRequest): Promise<InventoryReservationResult> {
    return {
      reservationId: `res_${request.orderId}`,
      status: request.lines.length ? 'reserved' : 'rejected',
      rejectedLines: request.lines.length ? [] : [{ variantId: 'unknown', reason: 'empty_reservation' }],
    };
  }
}

export class ReturnWorkflowService implements ReturnsService {
  async requestReturn(input: ReturnRequestInput): Promise<ReturnRequestResult> {
    const needsReview = input.reason.toLowerCase().includes('damage') || input.reason.toLowerCase().includes('wrong');
    return {
      returnId: `ret_${input.orderName.replace(/[^a-zA-Z0-9]/g, '').toLowerCase()}`,
      status: needsReview ? 'needs_review' : 'received',
      nextStep: needsReview ? 'Support will review the request before authorization.' : 'Return authorization can be generated by the returns workflow.',
    };
  }
}

export class CommerceOrchestrator {
  constructor(
    private readonly eventBus: EventBus,
    private readonly notifications: NotificationService,
    private readonly audit: AuditLogger,
    private readonly inventory: InventoryService,
    private readonly fraud: FraudDetectionService,
  ) {}

  async handleOrderCreated(orderId: string, reservation: InventoryReservationRequest, fraudRequest: FraudAssessmentRequest): Promise<void> {
    const fraudResult = await this.fraud.assess(fraudRequest);
    await this.audit.record('fraud.assessed', orderId, { ...fraudResult });
    if (fraudResult.decision === 'reject') {
      await this.notifications.enqueue({
        topic: 'order.created',
        recipient: 'admin',
        channel: 'admin',
        payload: { orderId, decision: fraudResult.decision },
      });
      return;
    }
    const reservationResult = await this.inventory.reserve(reservation);
    await this.audit.record('inventory.reserved', orderId, { ...reservationResult });
    await this.eventBus.publish({
      topic: 'order.created',
      anonymousId: 'system',
      payload: { orderId, fraudResult, reservationResult },
      occurredAt: new Date().toISOString(),
    });
  }
}
